name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # todo dia
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Gerar Pac-Man (Modo Escuro)
        run: |
          npm install -g pacman-contribution-graph
          mkdir -p dist
          pacman-contribution-graph --game pacman --platform github --username Luiirye --gameTheme github-dark --output dist/pacman-contribution-graph.svg
          
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
